---
# aide: CCE-27096-7
# xinetd: CCE-27354-0
# telnet: CCE-27401-9
# rsh: CCE-27342-5
# yp*: CCE-27385-4
# tftp: CCE-80213-2
# talk: CCE-27432-4
# sshd: CCE-80215-7
# avahi: CCE-80338-7
# UBTU-16-010010
# UBTU-16-010050

- name: debian family package installation
  become: 'yes'
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: 'no'
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  with_items:
    - "{{ packages_debian }}"
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages
    - security

- name: fedora epel installation
  become: 'yes'
  become_method: sudo
  package:
    name: "epel-release"
    state: latest
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon" and ansible_distribution != "Fedora"
  tags:
    - yum
    - packages
    - security

- name: Enable EPEL
  command: yum-config-manager --enable epel
  when: ansible_distribution == "Amazon"

#- name: Add EPEL repo
#  yum_repository:
#    name: epel_repo
#    description: EPEL YUM repo
#    baseurl:  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#  when: ansible_distribution == "Amazon"

- name: Import Fedora GPG key.
  rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7Server
    state: present
  when: ansible_distribution == "Amazon"

- name: redhat family package installation
  become: 'yes'
  become_method: sudo
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages_redhat }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  notify:
    - enable haveged
  tags:
    - yum
    - packages
    - security

- name: Amazon family package installation
  become: 'yes'
  become_method: sudo
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages_amazon }}"
  when: ansible_distribution == "Amazon"
  notify:
    - enable haveged
  tags:
    - yum
    - packages
    - security

- name: debian family package removal
  become: 'yes'
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: absent
    purge: 'yes'
  with_items:
    - "{{ packages_blacklist }}"
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - apt
    - packages
    - security

- name: redhat family package removal
  become: 'yes'
  become_method: sudo
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ packages_blacklist }}"
  when: ansible_os_family == "RedHat"
  tags:
    - yum
    - packages
    - security

- name: virtualbox package installation
  become: 'yes'
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: 'no'
  with_items:
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
  when: ansible_bios_version == "VirtualBox" and ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages
    - virtualbox
    - security

- name: vmware package installation
  become: 'yes'
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: 'no'
  with_items:
    - open-vm-tools
  when: ansible_bios_version == "VMWare"
  tags:
    - apt
    - yum
    - packages
    - vmware
    - security
...
