---
# https://github.com/ansible/ansible/issues/22171
- name: restart auditd
  systemd:
    name: auditd
    state: restarted

- name: generate auditd
  become: 'yes'
  become_method: sudo
  command: augenrules

- name: restart sysctl
  become: 'yes'
  become_method: sudo
  service:
    name: systemd-sysctl
    state: restarted

- name: reload systemd
  become: 'yes'
  become_method: sudo
  command: systemctl daemon-reload

- name: rkhunter propupd
  become: 'yes'
  become_method: sudo
  command: rkhunter --propupd

- name: enable aidecheck
  become: 'yes'
  become_method: sudo
  systemd:
    name: aidecheck.timer
    enabled: 'yes'
    state: started

- name: disable aidecheck
  become: 'yes'
  become_method: sudo
  systemd:
    name: aidecheck.timer
    state: stopped
    enabled: 'no'

- name: mask aidecheck
  become: 'yes'
  become_method: sudo
  systemd:
    name: aidecheck.timer
    masked: 'yes'
    stated: stopped
    enabled: 'no'

- name: restart sshd
  become: 'yes'
  become_method: sudo
  service:
    name: sshd
    state: restarted

- name: apt-get autoremove
  become: 'yes'
  become_method: sudo
  apt:
    autoremove: 'yes'

- name: apt-get clean
  become: 'yes'
  become_method: sudo
  apt:
    autoclean: 'yes'

- name: mask apport
  become: 'yes'
  become_method: sudo
  systemd:
    name: apport.service
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: mask motdnews
  become: 'yes'
  become_method: sudo
  systemd:
    name: motd-news.timer
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: yum clean
  become: 'yes'
  become_method: sudo
  command: yum -y clean all

- name: yum makecache
  become: 'yes'
  become_method: sudo
  command: yum -y makecache

- name: enable haveged
  become: 'yes'
  become_method: sudo
  systemd:
    name: haveged
    enabled: 'yes'
    state: started
  when: ansible_distribution != "Amazon"

- name: update authconfig
  become: 'yes'
  become_method: sudo
  command: authconfig --updateall
...
